name: Build macOS Universal2 Binary with PyInstaller

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-universal2:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up universal2 Python from python.org
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Ensure pip, wheel, setuptools are up to date
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install PyInstaller 6.0.0+ (for universal2 build)
        run: pip install "pyinstaller>=6.0.0"

      - name: Build universal2 app
        run: pyinstaller --onefile --target-architecture=universal2 --name rhythm-trainer main.py --distpath dist/universal2

      - name: Upload universal2 binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal2-app
          path: dist/universal2/
